Xpath_Country_Select = "//select[@id='landing-currency']"
Xpath_Enter_Btn = "//button[@value='Enter']"
Xpath_Men_Btn = "//a[@id='ui-id-68']//span[@class='mm-subcategory-title underline-megamenu ' or contains(text(),'Men')]"
Xpath_Shop_Now = "//div[@class='col-xs-12 col-sm-6 nopaddingright mg-top-20-mob']//img"
Xpath_Add_Bag = "//span[@class='product-image-container product-image-container-342013']//img"
Xpath_Choose_Size = "//div[@option-tooltip-value='M' or @aria-label='Medium']"
Xpath_Add_Cart = "//button[@id='product-addtocart-button']"
Xpath_Check_Out = "//button[@id='top-cart-btn-checkout']"
Xpath_Price = "//span[@id='product-price-342013']"
Xpath_email = "//input[@id='customer-email']"
Xpath_fname = "//input[@name='firstname']"
Xpath_lname = "//input[@name='lastname']"
Xpath_address = "//input[@name='street[0]']"
Xpath_state = "//input[@name='region']"
Xpath_city = "//select[@class='select' and @name='city']"
Xpath_zip = "//input[@name='postcode']"
Xpath_phone = "//input[@name='telephone']"
Xpath_next = "//button[@data-role='opc-continue' or @class='button action continue primary']"
Xpath_Email_word = "//div[@class='step-title' and contains(text(),'Shipping Address')]"
