Xpath_Country_Select = "//div[@class='field-holder country-select']"
Xpath_Country_Choice = "//div[@class='select-items']//div[text()='Pakistan']"
Xpath_Enter_Btn = "//input[@class='btn' and @type='submit' and @value='ENTER']"
Xpath_Shop_Now = "/html/body/div[2]/header/div/div/div/div[2]/div/div/div/div/div/div/p/a/strong/u"
Xpath_Add_Bag = "//*[@id='product-search-results']/div[2]/div[2]/div[2]/div[2]/div/div/div[1]/a[2]"
Xpath_Choose_Size = "//input[@id='010']"
Xpath_Add_Cart = "//*[@id='quickViewModal']/div/div/div[2]/div/div/div[2]/div[2]/section/div[5]/div[2]/div/div[2]/div/div"
Xpath_Check_Out = "//*[@id='productAddedSuccess']/div/div/div[2]/div[3]/div/a"
Xpath_Email_Box = "//*[@id='email-guest']"
Xpath_Fname_Box = "//*[@id='shippingFirstNamedefault']"
Xpath_Lname_Box = "//*[@id='shippingLastNamedefault']"
Xpath_Mobile_Box = "//*[@id='shippingPhoneNumberdefault']"
Xpath_Address_Box = "//*[@id='shippingAddressOnedefault']"
Xpath_Province_Select = "//*[@id='shippingStatedefault shippingState']"
Xpath_City_Select = "//*[@id='shippingCitydefault']"
Xpath_City_Choice = "//*[@id='shippingCitydefault']/option[2]"
Xpath_Proceed_Payment = "//*[@id='checkout-main']/div[3]/div[1]/div[12]/div/div/button[1]"