Xpath_Country_Select = "//div[@class='field-holder country-select']"
Xpath_Country_Choice = "//div[@class='select-items']//div[text()='Pakistan']"
Xpath_Enter_Btn = "//input[@class='btn' and @type='submit' and @value='ENTER']"
Xpath_Shop_Now = "//a//strong//u[contains(text(),'Shop Now.')]"
Xpath_Add_Bag = "//div[@data-uuid='11cb54b702a0a9c83d6cada608']//a[@class='quickview position-static product-tile-id cart-to-add btn btn-primary p-0']"
Xpath_Choose_Size = "//input[@id='010']"
Xpath_Add_Cart = "//button[@class='add-to-cart-global btn btn-primary']"
Xpath_Check_Out = "//a[@class='btn-go-to-checkout  ' or contains(text(),'Checkout')]"
Xpath_Email_Box = "//input[@id='email-guest']"
Xpath_Fname_Box = "//input[@id='shippingFirstNamedefault']"
Xpath_Lname_Box = "//input[@id='shippingLastNamedefault']"
Xpath_Mobile_Box = "//input[@id='shippingPhoneNumberdefault']"
Xpath_Address_Box = "//input[@id='shippingAddressOnedefault']"
Xpath_Province_Select = "//select[@id='shippingStatedefault shippingState']"
Xpath_City_Select = "//select[@id='shippingCitydefault']"
Xpath_City_Choice = "//*[@id='shippingCitydefault']/option[2]"
Xpath_Proceed_Payment = "//button[@class='btn btn-primary btn-block submit-shipping']"
